FROM pypy:2-5

WORKDIR /opt/LumberMill

COPY requirements.txt ./
COPY requirements-pypy.txt ./
RUN pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir -r requirements-pypy.txt \
 && rm -f /opt/LumberMill/requirements.txt \
 && rm -f /opt/LumberMill/requirements-pypy.txt \
