version: '2'
services:
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
  elasticsearch:
    image: 'elasticsearch:6.4.1'
    container_name: elasticsearch
    volumes:
      - /Users/bjorn/tmp:/usr/share/elasticsearch/data
    ports: ['9200:9200']
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m 
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  lumbermill:
    build: './lumbermill-python2'
    container_name: 'lumbermill-python2'
    entrypoint: '/bin/bash -c "while true; do sleep 1; done"'
    volumes:
      - $PWD/../:/opt/LumberMill
    ports:
      - '5151:5151'
      - '5252:5252'
    depends_on:
      - redis
      - elasticsearch
      - mongodb

  filebeat:
    image: 'docker.elastic.co/beats/filebeat:6.2.4'
    container_name: 'filebeat'
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    volumes:
 #     - './filebeat/test.log:/var/log/test.log'
      - './filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
 # kafka:
 #   image: "wurstmeister/kafka:latest"
 #   ports:
 #    - "9092:9092"
 #   hostname: kafka
 #   links:
 #    - zookeeper
 #   environment:
 #    - KAFKA_ADVERTISED_HOST_NAME=kafka
 #    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
 #    - KAFKA_ADVERTISED_PORT=9092
 # zookeeper:
 #   image: wurstmeister/zookeeper
 #   container_name: zookeeper
 #   ports:
 #     - "2181:2181"
