#!/bin/sh
#
# GambolPutty
#
# chkconfig:   2345 80 20
# description: Starts and stops a single GambolPutty instance on this system
#

### BEGIN INIT INFO
# Provides: GambolPutty
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: This service manages the GambolPutty daemon
### END INIT INFO

#
# init.d / servicectl compatibility (openSUSE)
#
if [ -f /etc/rc.status ]; then
    . /etc/rc.status
    rc_reset
fi

#
# Source function library.
#
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

# Source the pythonpath
. /etc/profile.d/python.sh

interpreter="/usr/bin/pypy"
exec="/opt/GambolPutty/src/GambolPutty.py"
prog="gambolputty"
pidfile=/var/run/gambolputty/${prog}.pid
lockfile=/var/lock/subsys/$prog
conffile=/etc/gambolputty/log2elasticsearch.conf

start() {
    [ -x $exec ] || exit 5
    [ -f $conffile ] || $(echo "Config $conffile does not exists!" && exit 6)
    echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $exec"
    daemonize -u $USER -p $pidfile -l $lockfile $interpreter $exec -c $conffile && success || failure $"$prog start"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
